# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.6.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-08-20T15:25:51Z"
  labels:
    app: timeweb-getssl-pod
  name: timeweb-getssl-pod
spec:
  initContainers:
    - name: preset
      image: askarini/timeweb-getssl:0.0.3
      command:
        - "/bin/sh"
        - "-c"
        - "cp -n $HOME/src/getssl.cfg $HOME/.getssl/getssl.cfg"
      volumeMounts:
        - mountPath: /getssl/.getssl
          name: cert-dir
  containers:
    - image: askarini/timeweb-getssl:0.0.3
      name: timeweb-getssl
      tty: true
      stdin: true
      #command: ["/bin/bash"] # uncomment this on first run to execute `getssl -c ...`
      env:
        - name: TWC_CONFIG_FILE
          value: /path/to/twc/config
      volumeMounts:
        - mountPath: /getssl/.getssl
          name: cert-dir
  volumes:
    - hostPath:
        path: /path/to/certificates/directory
        type: Directory
      name: cert-dir

